### ISSUE TITLE
Add support for streaming chunks

### ISSUE THREAD

**Issue by alexheretic** [lpenz/tokio-process-stream#1]
I'd like to listen to _ffmpeg_ output, however it prints over the same line with `\r` so `ProcessStream` will not yield this non-line at runtime.

Having another stream type that returns chunks would allow eager streaming of such output.

**Comment by alexheretic** [comment]
@lpenz it would be great to have this feature published on crates.io

**Comment by lpenz** [comment]
Done!
Thank you for doing this btw
